# This file contains values from Cookiecutter

default_context:
  project_name: "python-ml-project-api"
  project_slug: "python_ml_project_api"
  project_description: "Awesome `python-ml-project-api` project!"
  username: "Awesome user"
  email: "awesome-user@example.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.9"
  version: "0.1.0"
  line_length: "88"

  python_linter: "ruff"
  python_formatter: "ruff"

  include_mypy_type_checker: "y"
  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "y"
  include_notebooks_sample: "y"
