services:
  ml-api-server:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG:-latest}
    build:
      # Build from root
      context: ../
      dockerfile: docker/Dockerfile
    command: /run-main-app.sh
    ports:
      - "${ML_API_SERVER_PORT:-8080}:8080"
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  ml-api-worker:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG:-latest}
    command: /run-celery-worker.sh
    depends_on:
      - ml-api-server
      - redis
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  celery-flower:
    image: mher/flower:2.0
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:7.4-alpine
    volumes:
      - "redis_data:/data"
    logging:
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  redis_data:
