username: "Awesome user"

# This is an example of logger configuration from file
logger:
  version: 1
  disable_existing_loggers: true

  formatters:
    brief:
      format: '%(message)s'
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
    none:
      class: logging.NullHandler

  root:
    level: WARNING
    handlers: []

  loggers:
    python_ml_project_api.example:
      level: INFO
      handlers: [console]
      propogate: false
